#This code is auto generated code, don't Edit it 
chefjoinjs = ["js/chefjoin.js?reload"];
if (1): 
  chefjoinjs = myadd(chefjoinjs, ["https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=drawing,places&callback=initMap"]);
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height(cod([("val", 100)]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("errorbox");
outpvar.cur.fcalldata["main2"].addchilds(newtag_errorbox(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["errorbox"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Name"), ("id", "name")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Mobile number"), ("id", "mobile"), ("dc", "phone")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Email Id"), ("id", "email"), ("dc", "email")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Address [Select your Area from Google Search]"), ("id", "gaddress"), ("attr", cod([("onkeydown", "return notenterkey(event);")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Extra Address [Building#/Apartment#/Street Name/Land Mark]"), ("id", "address")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Choose a password"), ("id", "password"), ("dc", "password1"), ("type", "password")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("select2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_select2(cod([("tlist", ["Male", "Female"]), ("vlist", ["M", "F"]), ("toptext", "Gender"), ("name", "gender")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("select2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_select2(cod([("tlist", ginp["config"]["chefagelist"]), ("toptext", "Age"), ("name", "age")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("select2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_select2(cod([("tlist", ginp["config"]["chefhowmanypeople"]), ("toptext", "How many plates are you comfortable cooking in 1 meal"), ("name", "cookpeople")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("mselect2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_mselect2(cod([("id", "languages"), ("tlist", ginp["config"]["cheflanguages"]), ("label", "Select languages"), ("selectall", "Select All")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["mselect2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("switch2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_switch2(cod([("label", "Do you cook NonVeg Food"), ("name", "isnonveg")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["switch2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("switch2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_switch2(cod([("label", "Do you have academic degree in cooking ?"), ("class", "col l6"), ("name", "isdegree")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["switch2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textarea1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textarea1(cod([("label", "Please enter few of your signature dishes"), ("class", "materialize-textarea"), ("id", "dishes")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textarea1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_button1(cod([("name", "Submit"), ("attr", cod([("type", "button")])), ("data", cod([("onclick", "sreq"), ("fobj", ""), ("action", "chefjoinus"), ("restext", "Submitted"), ("errorh", "error_login"), ("res", "ms.thanksforapply(obj);")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", chefjoinjs)]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);