#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
blogurl = "";
tablink1 = [blogurl];
tabname1 = ["Blog"];
withChart = ["Total Power Generation", "Coal Power Generation", "Ntpc Power Generation", "Gas Power Generation", "Hydro Power Generation"];
rowkeysdef2 = ginp["rowExtra1"].keys();
rowkeysdef = ginp["rows"].keys();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container"), ("id", "mohitsaini")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("input2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input2(cod([("id", "date"), ("label", "Date"), ("iclass", "datepicker"), ("placeholder", "DD-MM-YYYY")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_button1(cod([("attr", cod([("type", "submit")])), ("name", "Submit")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "maindata")]))));
for jj in forlist(withChart, True ) :
  j = withChart[jj];
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("id", rowkeysdef[jj]), ("style", cod([("color", "black")]))]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "owl-carousel owl-theme")]))));
  for i in forlist(3, False ) :
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "maindiv1"), ("style", cod([])), ("attr", cod([("align", "center")]))]))));
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px")]))]))));
    outpvar.cur.fcalldata["main2"].addtext(j);
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].addtext(ginp["labeltext"][i]);
    outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("class", "actualtext")]))));
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "ringdiv")]))));
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px")]))]))));
  outpvar.cur.fcalldata["main2"].addtext(j);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(ginp["compMYTD"][0]);
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("id", ginp["ChartName"][jj])]))));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px")]))]))));
  outpvar.cur.fcalldata["main2"].addtext(j);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(ginp["compMYTD"][1]);
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("id", ginp["ChartName"][myadd(jj, 5)])]))));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("hr", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("id", "energy_shortage")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "owl-carousel owl-theme")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "maindiv1"), ("style", cod([])), ("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Total Energy Shortage");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext(ginp["labeltextExtra1"][0]);
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("class", "actualtext")]))));
outpvar.cur.fcalldata["main2"].addtext("Actual Shortage =");
outpvar.cur.fcalldata["main2"].addtext(myadd(ginp["rows"]["energy_shortage"][0]["tbl_energy_shortage_daily"][0]["actual"], "%"));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext("Target Shortage =");
outpvar.cur.fcalldata["main2"].addtext(myadd(ginp["rows"]["energy_shortage"][0]["tbl_energy_shortage_daily"][0]["target"], "%"));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "ringdiv")]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("hr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("id", "peak_power_shortage")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "owl-carousel owl-theme")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "maindiv1"), ("style", cod([])), ("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Peak Power Shortage");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext(ginp["labeltextExtra2"][0]);
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("class", "actualtext")]))));
outpvar.cur.fcalldata["main2"].addtext("Actual Shortage =");
outpvar.cur.fcalldata["main2"].addtext(myadd(ginp["rows"]["peak_power_shortage"][0]["tbl_peak_power_shortage_daily"][0]["actual"], "%"));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext("Target Shortage =");
outpvar.cur.fcalldata["main2"].addtext(myadd(ginp["rows"]["peak_power_shortage"][0]["tbl_peak_power_shortage_daily"][0]["target"], "%"));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "ringdiv")]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("hr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([])), ("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px"), ("color", "red")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Critical Coal Plants");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext("Number of ");
outpvar.cur.fcalldata["main2"].addtext(ginp["labeltextcritical"][0]);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "200px"), ("color", "green")]))]))));
outpvar.cur.fcalldata["main2"].addtext(ginp["scritical"]["tbl_super_critical_coal_plant"][0]["number"]);
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("hr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([])), ("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px"), ("color", "red")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Super Critical Coal Plants");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext("Number of Super ");
outpvar.cur.fcalldata["main2"].addtext(ginp["labeltextcritical"][0]);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "200px"), ("color", "green")]))]))));
outpvar.cur.fcalldata["main2"].addtext(ginp["scritical"]["tbl_super_critical_coal_plant"][0]["number"]);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("hr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", ["js/index.js?reload"])]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);