#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
blogurl = "";
tablink1 = [blogurl];
tabname1 = ["Blog"];
outpvar.cur.fcalldata["main2"].cur.addfcdata("header1_power");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header1_power(cod([("tabname", ginp["tabs"]), ("tablink", ginp["rowkeydef_href"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header1_power"].root.content).root.content);
rowkeysdef = ginp["rows"].keys();
outpvar.cur.fcalldata["main2"].addtext("random check");
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container"), ("id", "mohitsaini")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("input2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input2(cod([("id", "date"), ("label", "Date"), ("iclass", "datepicker"), ("placeholder", "DD-MM-YYYY")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_button1(cod([("attr", cod([("type", "submit")])), ("name", "Submit")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "maindata")]))));
for jj in forlist(ginp["rowkeys"], True ) :
  j = ginp["rowkeys"][jj];
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("id", rowkeysdef[jj])]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "owl-carousel owl-theme")]))));
  for i in forlist(5, False ) :
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "maindiv1"), ("style", cod([])), ("attr", cod([("align", "center")]))]))));
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "center")]))]))));
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "40px")]))]))));
    outpvar.cur.fcalldata["main2"].addtext(j);
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].addtext(ginp["labeltext"][i]);
    outpvar.cur.fcalldata["main2"].open(htmlnode("br", extentattrs(cod([]))));
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("class", "actualtext")]))));
    outpvar.cur.fcalldata["main2"].addtext("Saini");
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "ringdiv")]))));
    outpvar.cur.fcalldata["main2"].close();
    outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("hr", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", ["js/index.js?reload"])]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);